load("//nasm:nasm_toolchain.bzl", "nasm_toolchain")

[
    alias(
        name = name,
        actual = "//platforms:{}_constraint".format(name),
        visibility = ["//visibility:public"],
    )
    for name in [
        "elf64",
        "macho64",
        "win64",
    ]
]

nasm_toolchain(
    name = "nasm_toolchain",
    copts = select({
        ":elf64": ["-felf64"],
        ":macho64": ["-fmacho64"],
        ":win64": ["-fwin64"],
        "//conditions:default": [],
    }),
    nasm = "@nasm",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchain",
    toolchain = ":nasm_toolchain",
    toolchain_type = "//nasm:toolchain_type",
    visibility = ["//visibility:public"],
)
